pool:
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.0.100-preview.7.21379.14'
    includePreviewVersions: true
    
- task: PowerShell@2
  inputs:
    targetType: 'filePath'
    filePath: $(System.DefaultWorkingDirectory)\buildandtest.ps1
    ignoreLASTEXITCODE: false
  displayName: 'Build Example solutions and run tests'