pool:
  vmImage: 'windows-2022'

steps:
- task: CmdLine@2
  inputs:
    script: 'dotnet dev-certs https --trust'
    
- task: PowerShell@2
  inputs:
    targetType: 'filePath'
    filePath: $(System.DefaultWorkingDirectory)\buildandtest.ps1
    ignoreLASTEXITCODE: false
  displayName: 'Build Example solutions and run tests'