// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.2.0.0
//      Runtime Version:2.0.50727.4927
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace BookShop.Specs.Web
{
    using TechTalk.SpecFlow;
    
    
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Order Submission")]
    public partial class OrderSubmissionFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "03_OrderSubmission.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en"), "Order Submission", "In order to buy books\r\nAs a customer\r\nI want to checkout my cart and commit the o" +
                    "rder.", ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            this.FeatureBackground();
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
  #line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Author",
                        "Title",
                        "Price"});
            table1.AddRow(new string[] {
                        "Book1",
                        "Martin Fowler",
                        "Patterns of Enterprise Architecture",
                        "10,05"});
            table1.AddRow(new string[] {
                        "Book2",
                        "Eric Evans",
                        "Domain Driven Design",
                        "15,10"});
            table1.AddRow(new string[] {
                        "Book3",
                        "Ted Pattison",
                        "Inside Windows SharePoint Services",
                        "9,75"});
#line 7
 testRunner.Given("the following books", ((string)(null)), table1);
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Committing a simple order")]
        public virtual void CommittingASimpleOrder()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Committing a simple order", ((string[])(null)));
#line 13
  this.ScenarioSetup(scenarioInfo);
#line 14
 testRunner.When("I put a book into my shopping cart");
#line 15
    testRunner.When("I check out the cart");
#line 16
    testRunner.Then("an order should be created");
#line 17
    testRunner.And("the order should have 1 line item");
#line 18
    testRunner.And("the price of the order should be set");
#line 19
    testRunner.And("the order status should be \'InProgress\'");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
