// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.2.0.0
//      Runtime Version:2.0.50727.4927
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace BookShop.Specs.Web
{
    using TechTalk.SpecFlow;
    
    
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Shopping cart 2")]
    public partial class ShoppingCart2Feature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "x02_ShopingCart.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en"), "Shopping cart 2", "As a potential customer\r\nI want to place books into my shopping basket\r\nSo that I" +
                    " can order several books at once.", ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            this.FeatureBackground();
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
  #line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Author",
                        "Title",
                        "Price"});
            table1.AddRow(new string[] {
                        "Book1",
                        "Martin Fowler",
                        "Patterns of Enterprise Architecture",
                        "10,05"});
            table1.AddRow(new string[] {
                        "Book2",
                        "Eric Evans",
                        "Domain Driven Design",
                        "15,10"});
            table1.AddRow(new string[] {
                        "Book3",
                        "Ted Pattison",
                        "Inside Windows SharePoint Services",
                        "9,75"});
#line 7
 testRunner.Given("the following books", ((string)(null)), table1);
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Navigation: Putting a book into the shopping cart")]
        public virtual void NavigationPuttingABookIntoTheShoppingCart()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Navigation: Putting a book into the shopping cart", ((string[])(null)));
#line 13
  this.ScenarioSetup(scenarioInfo);
#line 14
 testRunner.When("I put a book into my shopping cart");
#line 15
    testRunner.Then("the resulting page should be \'ShoppingCart\'");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Putting one book into the shopping cart")]
        public virtual void PuttingOneBookIntoTheShoppingCart()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Putting one book into the shopping cart", ((string[])(null)));
#line 17
  this.ScenarioSetup(scenarioInfo);
#line 18
 testRunner.When("I put a book into my shopping cart");
#line 19
    testRunner.Then("my shopping cart should contain 1 item");
#line 20
    testRunner.And("the total price should be set");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Removing a line item from the shopping cart")]
        public virtual void RemovingALineItemFromTheShoppingCart()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Removing a line item from the shopping cart", ((string[])(null)));
#line 22
  this.ScenarioSetup(scenarioInfo);
#line 23
 testRunner.When("I put a book into my shopping cart");
#line 24
    testRunner.Then("my shopping cart should contain 1 item");
#line 25
    testRunner.When("I remove the first line item of my shopping cart");
#line 26
    testRunner.Then("my shopping cart should contain 0 item");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Editing a line item of the shopping cart")]
        public virtual void EditingALineItemOfTheShoppingCart()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Editing a line item of the shopping cart", ((string[])(null)));
#line 28
  this.ScenarioSetup(scenarioInfo);
#line 29
 testRunner.When("I put a book into my shopping cart");
#line 30
    testRunner.Then("my shopping cart should contain 1 item");
#line 31
    testRunner.And("the quantity should be \'1\'");
#line 32
    testRunner.When("I increase the quantity of the line item by \'1\'");
#line 33
    testRunner.Then("my shopping cart should contain 1 item");
#line 34
    testRunner.And("the quantity should be \'2\'");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
