version: '3.4'

services:
  communitycontentsubmissionpage:
    image: ${DOCKER_REGISTRY-}communitycontentsubmissionpage
    build:
      context: .
      dockerfile: CommunityContentSubmissionPage/Dockerfile
    ports:
      - "6969:5000"
      - "6970:5001"
      - "80"
      - "443"
    environment:
      - CommunityContent_ConnectionString=Server=db;Database=Content;User=sa;Password=Password123%
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
    depends_on:
      - db
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports: 
      - "42068:1433"
    environment:
      SA_PASSWORD: Password123%
      ACCEPT_EULA: "Y"
